from app.models.schemas import (
    AgentPromptContract,
    AgentStrategy,
    LangGraphEdgeContract,
    LangGraphNodeContract,
    LangGraphWorkflowContract,
)


MAIN_PLANNING_AGENT_STRATEGY = [
    AgentStrategy(
        name="InteractionRouterAgent",
        responsibility="判断本轮用户输入是新规划、补全回答、确认需求、微调当前方案、切换任务还是普通问答。",
        inputs=["RoutePlanRequest.goal", "RoutePlanRequest.plan_mode", "RoutePlanRequest.interaction_context"],
        outputs=["interaction_type", "intent_kind", "routing_reason"],
        tools=["deterministic_interaction_router", "llm_router_fallback"],
        handoff_conditions=["interaction_type 已确定", "普通问答转 ChatAnswerAgent", "主规划转 ConstraintDiscoveryAgent"],
        failure_fallback="Plan 模式打开时偏向 new_planning_task，关闭时偏向 chat_answer；方案页局部修改偏向 refine_current_plan。",
        trace_events=["agent_started", "tool_called", "task_switched", "handoff"],
        runtime_role="main_planning",
        llm_call_budget=1,
        react_step_budget=2,
        latency_budget_ms=500,
    ),
    AgentStrategy(
        name="ConstraintDiscoveryAgent",
        responsibility="拆解本轮用户目标和全部语义约束，区分硬约束/软约束，维护 Constraint Ledger，并决定是否追问。",
        inputs=["RoutePlanRequest", "interaction_type", "existing ConstraintLedger"],
        outputs=["constraint_ledger", "requirement_summary", "clarification_cards"],
        tools=["mock_intent_parser", "deterministic_clarification_card_builder", "schema_validator"],
        handoff_conditions=["阻塞字段已补齐，或已返回 clarification_cards 等用户回答"],
        failure_fallback="对非阻塞字段使用默认假设；缺城市/区域、时间窗、人数、是否安排吃喝时返回结构化追问。",
        trace_events=["agent_started", "tool_called", "constraint_discovered", "clarification_requested", "requirements_summarized", "handoff"],
        runtime_role="main_planning",
        llm_call_budget=1,
        react_step_budget=4,
        latency_budget_ms=1800,
    ),
    AgentStrategy(
        name="UserPreferenceAgent",
        responsibility="读取历史收藏、评分、去过的店和用户 UGC 评价，形成长期偏好约束；首次进入可异步预热。",
        inputs=["user_id", "ConstraintLedger", "RoutePlanRequest.constraints"],
        outputs=["preference_profile", "preference_constraints", "priority_weights"],
        tools=["mock_user_profile_lookup", "detect_and_store_preferences"],
        handoff_conditions=["偏好缓存已读取，或已标记 preference_warmup_pending 并继续主规划"],
        failure_fallback="使用匿名低排队、少走路、推荐理由清楚的默认画像。",
        trace_events=["agent_started", "tool_called", "preference_detected", "handoff"],
        runtime_role="main_planning",
        llm_call_budget=1,
        react_step_budget=3,
        latency_budget_ms=900,
        parallelizable=True,
    ),
    AgentStrategy(
        name="ContextGroundingAgent",
        responsibility="并行调用天气、交通、地图、POI、营业时间、排队预测、UGC 和推荐菜 provider，把约束落成可信事实。",
        inputs=["ConstraintLedger", "preference_profile", "provider contracts"],
        outputs=["grounded_context", "candidate_pois", "route_matrix", "poi_fact_pack"],
        tools=[
            "provider_adapter.poi_search",
            "provider_adapter.route_matrix",
            "provider_adapter.weather",
            "provider_adapter.mock_deep_poi_enrichment",
        ],
        handoff_conditions=["候选 POI、地图距离、营业/排队/UGC 事实均已写入 Constraint Ledger"],
        failure_fallback="缺失 provider 时使用 deterministic mock provider，并把 reliability 标记为 mocked 或 predicted。",
        trace_events=["agent_started", "tool_called", "context_grounded", "candidate_retrieved", "map_context_resolved", "handoff"],
        runtime_role="main_planning",
        llm_call_budget=0,
        react_step_budget=6,
        latency_budget_ms=2500,
        parallelizable=True,
    ),
    AgentStrategy(
        name="PlanSolverAgent",
        responsibility="基于约束账本生成多个候选 plan，安排 POI 组合、顺序、到达时间、停留时长和交通方式。",
        inputs=["ConstraintLedger", "grounded_context", "candidate_pois", "route_matrix"],
        outputs=["candidate_plans", "stop_schedule", "solver_notes"],
        tools=["slot_based_route_builder", "beam_search_candidate_solver", "mock_route_scheduler"],
        handoff_conditions=["至少生成 3 个候选方案，或标记 planner_fallback 并返回兜底方案"],
        failure_fallback="使用同商圈、低排队、营业稳定的三站路线模板。",
        trace_events=["agent_started", "tool_called", "route_candidate_generated", "handoff"],
        runtime_role="main_planning",
        llm_call_budget=1,
        react_step_budget=4,
        latency_budget_ms=1800,
    ),
    AgentStrategy(
        name="PlanEvaluatorAgent",
        responsibility="校验候选 plan 是否违反约束，计算分数、拆解得分、排序，并在硬约束失败时要求 Solver 局部重算。",
        inputs=["candidate_plans", "ConstraintLedger", "preference_profile", "grounded_context"],
        outputs=["evaluated_plans", "score_breakdown", "rank_reason", "blocking_issues"],
        tools=["mock_constraint_checker", "mock_route_judge", "deterministic_score_breakdown"],
        handoff_conditions=["硬约束全部满足，固定输出 3 个可解释方案"],
        failure_fallback="有硬约束冲突时替换冲突 POI；无法替换时保留风险并显著降分。",
        trace_events=["agent_started", "tool_called", "constraint_checked", "route_scored", "handoff"],
        runtime_role="main_planning",
        llm_call_budget=1,
        react_step_budget=4,
        latency_budget_ms=1500,
    ),
    AgentStrategy(
        name="PlanExplanationAgent",
        responsibility="把最终 3 个方案解释给用户，生成标题、亮点、风险提醒、每个 POI 推荐理由和推荐菜展示。",
        inputs=["evaluated_plans", "ConstraintLedger", "poi_fact_pack", "score_breakdown"],
        outputs=["user_visible_plans", "stop_reasons", "risk_copy", "dish_recommendations"],
        tools=["mock_experience_copywriter", "llm_copywriter"],
        handoff_conditions=["每个方案和每个 stop 都有用户可读解释"],
        failure_fallback="使用 POI 标签、UGC 摘要、排队分钟数和约束检查结果拼接简短理由。",
        trace_events=["agent_started", "tool_called", "run_completed"],
        runtime_role="main_planning",
        llm_call_budget=1,
        react_step_budget=3,
        latency_budget_ms=1800,
    ),
]


CHAT_AGENT_STRATEGY = [
    MAIN_PLANNING_AGENT_STRATEGY[0],
    MAIN_PLANNING_AGENT_STRATEGY[2],
    MAIN_PLANNING_AGENT_STRATEGY[3],
    AgentStrategy(
        name="ChatAnswerAgent",
        responsibility="普通 POI 问答时读取少量相关 POI、偏好和 UGC 摘要，返回 answer + related_pois + trace。",
        inputs=["ChatRequest.message", "preference_profile", "related_pois"],
        outputs=["answer", "related_pois", "can_convert_to_plan"],
        tools=["mock_chat_poi_search", "mock_chat_answer"],
        handoff_conditions=["已给出可直接展示的回答和引用 POI"],
        failure_fallback="返回低排队、安静聊天和步行友好的默认 POI 建议。",
        trace_events=["agent_started", "tool_called", "chat_answered", "run_completed"],
        runtime_role="auxiliary",
        llm_call_budget=1,
        react_step_budget=3,
        latency_budget_ms=1400,
    ),
]


MOCK_DATA_AGENT_STRATEGY = [
    AgentStrategy(
        name="MockDataAgent",
        responsibility="在开发者/评审面板生成 Mock User、Mock POI、Mock UGC 和 Mock 环境数据，并通过 schema/provider 校验。",
        inputs=["mock generation request", "provider contracts"],
        outputs=["generated_mock_data", "validation_report", "fallback_used"],
        tools=["llm_mock_data_provider", "pydantic_validator", "mock_map_provider.geocode"],
        handoff_conditions=["生成数据通过 schema 校验并标记 provider reliability"],
        failure_fallback="LLM 失败时返回 deterministic_template，并标记 fallback_used=true。",
        trace_events=["agent_started", "tool_called", "run_completed"],
        runtime_role="auxiliary",
        llm_call_budget=2,
        react_step_budget=5,
        latency_budget_ms=3000,
    )
]


AGENT_PROMPT_CONTRACTS = [
    AgentPromptContract(
        agent_name="InteractionRouterAgent",
        objective="判断本轮输入应该进入哪条状态图路径。",
        input_schema="RoutePlanRequest + InteractionContext + optional previous AgentTrace",
        output_schema="interaction_type + intent_kind + routing_reason",
        tools=["deterministic_interaction_router"],
        max_llm_calls=1,
        max_react_steps=2,
        latency_budget_ms=500,
        guardrails=["页面状态是强提示，不是硬规则", "不能把普通 POI 问答误强制成完整路线"],
        fallback="Plan 模式打开时偏向 new_planning_task，关闭时偏向 chat_answer。",
    ),
    AgentPromptContract(
        agent_name="ConstraintDiscoveryAgent",
        objective="把用户目标、显性要求、隐性场景要求和缺失字段写入 Constraint Ledger。",
        input_schema="RoutePlanRequest + interaction_type + existing ConstraintLedger",
        output_schema="ConstraintLedger + RequirementSummary + ClarificationCard[]",
        tools=["schema_validator", "clarification_card_builder"],
        max_llm_calls=1,
        max_react_steps=4,
        latency_budget_ms=1800,
        guardrails=[
            "不能编造天气、交通、营业、排队、距离和推荐菜事实",
            "每个约束必须标注 source 和 reliability",
            "缺阻塞字段时必须输出 clarification_cards",
        ],
        fallback="对非阻塞字段写 assumptions；阻塞字段缺失时先追问。",
    ),
    AgentPromptContract(
        agent_name="UserPreferenceAgent",
        objective="把历史收藏、评分、去过的店和用户 UGC 评论总结成长期偏好约束。",
        input_schema="user_id + mock/real user history + ConstraintLedger",
        output_schema="preference_profile + preference_constraints + priority_weights",
        tools=["user_profile_store", "preference_summary_cache"],
        max_llm_calls=1,
        max_react_steps=3,
        latency_budget_ms=900,
        guardrails=["只输出与本次规划相关的偏好", "不能暴露完整隐私档案", "缓存未就绪时不得阻塞主规划"],
        fallback="使用匿名默认画像，并在 Trace 标记 preference_warmup_pending。",
    ),
    AgentPromptContract(
        agent_name="ContextGroundingAgent",
        objective="把约束账本中的待落地约束转换成 provider 可验证事实。",
        input_schema="ConstraintLedger + provider contracts + preference_profile",
        output_schema="grounded_context + candidate_pois + poi_fact_pack + updated ConstraintLedger",
        tools=["weather_provider", "traffic_provider", "poi_provider", "queue_provider", "ugc_provider", "map_provider"],
        max_llm_calls=0,
        max_react_steps=6,
        latency_budget_ms=2500,
        guardrails=["不得由 LLM 猜事实", "provider 缺失时必须标记 mocked/predicted", "距离和通勤统一由地图 provider 给出"],
        fallback="使用 deterministic mock provider，并把 reliability 标记为 mocked。",
    ),
    AgentPromptContract(
        agent_name="PlanSolverAgent",
        objective="从候选 POI 中生成多条可执行候选路线。",
        input_schema="ConstraintLedger + grounded_context + candidate_pois + route_matrix",
        output_schema="candidate_plans + solver_notes",
        tools=["slot_builder", "beam_search_solver", "route_scheduler"],
        max_llm_calls=1,
        max_react_steps=4,
        latency_budget_ms=1800,
        guardrails=["不能输出违反硬约束的方案", "不能自造 POI 或距离", "用户锁定 POI 时只改未锁定部分"],
        fallback="使用稳定三站模板并标记 planner_fallback。",
    ),
    AgentPromptContract(
        agent_name="PlanEvaluatorAgent",
        objective="检查候选路线的硬约束和软约束，输出评分拆解和排序理由。",
        input_schema="candidate_plans + ConstraintLedger + preference_profile + grounded_context",
        output_schema="evaluated_plans + score_breakdown + blocking_issues",
        tools=["constraint_checker", "score_calculator"],
        max_llm_calls=1,
        max_react_steps=4,
        latency_budget_ms=1500,
        guardrails=["硬约束失败必须淘汰或要求重算", "分数必须可拆解", "用户端不强调数学精确"],
        fallback="按硬约束满足率给基础分，缺少事实时降置信度并写风险提醒。",
    ),
    AgentPromptContract(
        agent_name="PlanExplanationAgent",
        objective="把最终 3 个方案解释成用户能懂的推荐理由和行动入口文案。",
        input_schema="evaluated_plans + ConstraintLedger + poi_fact_pack + score_breakdown",
        output_schema="user_visible_plans + stop_reasons + risk_copy + dish_recommendations",
        tools=["copywriter_llm", "template_fallback"],
        max_llm_calls=1,
        max_react_steps=3,
        latency_budget_ms=1800,
        guardrails=["只能解释已有事实", "不能编造推荐菜", "必须保留风险提醒"],
        fallback="用模板拼接 POI 标签、UGC 摘要和约束检查结果。",
    ),
]


LANGGRAPH_PLANNING_WORKFLOW = LangGraphWorkflowContract(
    name="dzultra_v3_planning_graph",
    state_schema=[
        "request",
        "interaction_type",
        "constraint_ledger",
        "preference_profile",
        "grounded_context",
        "candidate_pois",
        "candidate_plans",
        "evaluated_plans",
        "selected_plan_id",
        "trace_events",
        "retry_count",
        "fallback_flags",
    ],
    latency_budget_ms=10000,
    retry_policy={"PlanEvaluatorAgent": {"max_retries": 1, "on_hard_constraint_failure": "PlanSolverAgent"}},
    nodes=[
        LangGraphNodeContract(
            id="router",
            agent_name="InteractionRouterAgent",
            kind="agent",
            reads=["request", "trace_events"],
            writes=["interaction_type", "trace_events"],
            description="判断本轮输入的路径。",
        ),
        LangGraphNodeContract(
            id="constraint_discovery",
            agent_name="ConstraintDiscoveryAgent",
            kind="agent",
            reads=["request", "interaction_type", "constraint_ledger"],
            writes=["constraint_ledger", "requirement_summary", "clarification_cards", "trace_events"],
            description="发现目标和约束，并决定是否追问。",
        ),
        LangGraphNodeContract(
            id="wait_user_input",
            kind="wait",
            reads=["clarification_cards"],
            writes=["request"],
            description="等待用户回答补全卡片。",
        ),
        LangGraphNodeContract(
            id="user_preference",
            agent_name="UserPreferenceAgent",
            kind="agent",
            reads=["request.user_id", "constraint_ledger"],
            writes=["preference_profile", "constraint_ledger", "trace_events"],
            description="读取或预热长期偏好。",
        ),
        LangGraphNodeContract(
            id="context_grounding",
            agent_name="ContextGroundingAgent",
            kind="agent",
            reads=["constraint_ledger", "preference_profile"],
            writes=["grounded_context", "candidate_pois", "constraint_ledger", "trace_events"],
            description="调用 provider 落地天气、交通、地图、POI、排队、UGC 等事实。",
        ),
        LangGraphNodeContract(
            id="plan_solver",
            agent_name="PlanSolverAgent",
            kind="agent",
            reads=["constraint_ledger", "grounded_context", "candidate_pois"],
            writes=["candidate_plans", "trace_events"],
            description="生成多个候选方案。",
        ),
        LangGraphNodeContract(
            id="plan_evaluator",
            agent_name="PlanEvaluatorAgent",
            kind="agent",
            reads=["candidate_plans", "constraint_ledger", "grounded_context"],
            writes=["evaluated_plans", "selected_plan_id", "trace_events", "retry_count"],
            description="检查约束、打分排序，必要时要求 Solver 重算。",
        ),
        LangGraphNodeContract(
            id="plan_explanation",
            agent_name="PlanExplanationAgent",
            kind="agent",
            reads=["evaluated_plans", "constraint_ledger"],
            writes=["response", "trace_events"],
            description="生成用户可读解释。",
        ),
        LangGraphNodeContract(
            id="chat_answer",
            agent_name="ChatAnswerAgent",
            kind="agent",
            reads=["request", "preference_profile", "grounded_context"],
            writes=["chat_response", "trace_events"],
            description="普通 POI 问答。",
        ),
        LangGraphNodeContract(
            id="end",
            kind="terminal",
            reads=["response", "trace_events"],
            writes=[],
            description="返回 API response。",
        ),
    ],
    edges=[
        LangGraphEdgeContract(source="router", target="chat_answer", condition="interaction_type == chat_answer", description="普通问答走轻链路。"),
        LangGraphEdgeContract(source="router", target="constraint_discovery", condition="interaction_type != chat_answer", description="规划、补全、微调和切换任务进入约束发现。"),
        LangGraphEdgeContract(source="constraint_discovery", target="wait_user_input", condition="planning_status == needs_clarification", description="缺阻塞字段时等待用户补全。"),
        LangGraphEdgeContract(source="constraint_discovery", target="user_preference", condition="can_plan == true", description="需求可规划后读取偏好。"),
        LangGraphEdgeContract(source="user_preference", target="context_grounding", description="偏好约束加入账本后落地事实。"),
        LangGraphEdgeContract(source="context_grounding", target="plan_solver", description="事实约束和候选 POI 就绪后生成候选路线。"),
        LangGraphEdgeContract(source="plan_solver", target="plan_evaluator", description="候选路线进入校验和排序。"),
        LangGraphEdgeContract(source="plan_evaluator", target="plan_solver", condition="hard_constraints_failed and retry_count < 1", description="硬约束失败时局部重算一次。"),
        LangGraphEdgeContract(source="plan_evaluator", target="plan_explanation", condition="evaluated_plans.ready", description="评分排序完成后生成解释。"),
        LangGraphEdgeContract(source="plan_explanation", target="end", description="返回 3 个可解释方案。"),
        LangGraphEdgeContract(source="chat_answer", target="end", description="返回 answer + related_pois + trace。"),
    ],
)
